networks:
    traefik:
        external: true
services:
    baltimare-leaderboard:
        build: .
        restart: always
        labels:
            - traefik.enable=true
            - traefik.http.routers.baltimare-leaderboard.rule=Host(`baltimare.hotmilk.space`)
            - traefik.http.routers.baltimare-leaderboard.entrypoints=websecure
            - traefik.http.routers.baltimare-leaderboard.service=baltimare-leaderboard
            - traefik.http.routers.baltimare-leaderboard.tls.certResolver=le
            - traefik.http.services.baltimare-leaderboard.loadbalancer.server.port=8080
            - traefik.docker.network=traefik
        volumes:
            - ./db:/app/db
        networks:
            - default
            - traefik
